name: Replace-Tokens

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node-version: [ 16.x, 17.x, 18.x, 20.x ]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install (Clean), Build & Test
      run: |
          npm ci
          npm run build --if-present
          npm test