name: CVI DEPLOYMENT

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 20.x ]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Replace Tokens ( <<<<BlobDevelopment Example  >>>> )
      uses: BlobDevelopment/copy-and-replace-tokens@v2
      with:
        source: 'test/base.agathe.conf.template'
        target: './test/cvi.agathe.conf'
      env:
        SAP_NAME: CVI
        sap_remote_programid: AGT_COSMICINT_CVI010
        host: licvics310.sap.azure.cloud.bmw
        gwserv: 3310
        msserv: 3610
        repository_destination:  CVI_REG
        RCVPRN: CVICLNT010
        RCVPRT: LS
        SNDPRN: AGATHEINT
        SNDPOR: AGTAHE
        SNDPRT: LS
        kafka_bootstrap_servers: lkc-o0d1x-437zm.westeurope.azure.glb.confluent.cloud:9092
        kafka_consumer_group_id: bmw.cosmicintlfsm.connect.agathe.cvi
        kafka_streams_application_id: bmw.cosmicintlfsm.connect.agathe.streams.cvi
        kafka_pipelines_name : COSMICINTLFSM
        kafka_pipelines_topic: cosmicintlfsm

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        tag: Release
        
    - name: checkin updates
      run: |
        git config user.name "$(git log -n 1 --pretty=format:%an)"
        git config user.email "$(git log -n 1 --pretty=format:%ae)"
        git add .
        git commit -m "cvi latest changes"
        git push
